<div>
  <ul>
    <li>Templatecontent1 <test1>sdf</test1></li>
    <li>
      <test2>
        Templatecontent2
        <ul>
          <li>
            <test2.1>
              Templatecontent2.1
              <ul>
                <li><test2.1.1>xcv</test2.1.1></li>
                <li><test2.1.2>xcv</test2.1.2></li>
              </ul>
            </test2.1>
          </li>
          <li><test2.2>zui</test2.2>
        </ul>
      </test2>
    </li>
  </ul>
</div>